services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    networks:
      - ecommerce-local

  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - ecommerce-local

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-local
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - ecommerce-local

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-local
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ecommerce-local

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-local
    ports:
      - "9411:9411"
    networks:
      - ecommerce-local


networks:
  ecommerce-local:
    driver: bridge
