# 공통 설정
server:
  port: 8081
spring:
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:local}  # Config 서버에서 가져올 프로필
      fail-fast: true