# 공통 설정
server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:local}  # Config 서버에서 가져올 프로필
      fail-fast: true
  kafka:
    bootstrap-servers: localhost:9092


kafka:
  consumer:
    group-id: order-service
    auto-offset-reset: earliest
  topic:
    order-events: order-events
    payment-events: payment-events
    order-status-update: order-status-update
    product-stock-update: product-stock-update