# 공통 설정
server:
  port: 8080

spring:
  application:
    name: image-service
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:local}  # Config 서버에서 가져올 프로필
      fail-fast: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: image-service-group
    auto-offset-reset: earliest
  topic:
    image-storage: image-storage-topic
    image-find: image-find-topic
    image-id: image-id-topic
    image-lob: image-lob-topic