# 공통 설정
server:
  port: 8082

spring:
  application:
    name: product-service
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:local}  # Config 서버에서 가져올 프로필
      fail-fast: true
  kafka:
    bootstrap-servers: localhost:9092


kafka:
  consumer:
    group-id: product-service
    auto-offset-reset: earliest
  topic:
    image-storage: image-storage-topic
    image-find: image-find-topic
    image-id: image-id-topic
    order-status-update: order-status-update
    product-stock-update: product-stock-update