# ?? ??
server:
  port: 8086

spring:
  application:
    name: batch-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: D:/2025/e-commerce/logs/e-commerce-batch.log
  level:
    root: INFO
    com.commerce.batchservice: debug
